global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: [ "localhost:9090" ]

  - job_name: "concord-server"
    static_configs:
    - targets: {{ metricsHosts.concord.server | to_json }}

  - job_name: "node-host"
    static_configs:
    - targets: {{ metricsHosts.nodes | to_json }}

  - job_name: "pg-exporter"
    static_configs:
    - targets: {{ metricsHosts.concord.db | to_json }}
