---

- name: Install OS Prerequisites
  apt:
    name:
    - python3-setuptools
    - python3-pip
    update_cache: yes
  become: yes
  
- name: Install Python Docker Packge
  pip:
    name: "{{ item }}"
    umask: '0022'
    state: present
    executable: pip3
    extra_args: --ignore-installed docker
  become: yes
  with_items:
    - docker
    - cryptography
